-- ციკლი ეს არის პროგრამირების ინსტრუმენტი
-- რომელიც გვაძლაევს საშვალებას ერთი და იგივე
-- დავალება რამდენჯერმე გავამეორო

-- გვაქვს 3 ციკლი: for, while, repeat

-- start, stop, step
-- for ewryeruyeruyeri = 1, 10, 3 do
--     print(ewryeruyeruyeri)
-- end


--[[
1. for
2. საიტერაციო ცვლადი
3. do
4. კოდის ბლოკი ინდენტაციით
5. end
]]


-- Position:   1     2   3

-- for i = 1, #data do
--     print(data[i])
-- end


local data = {true, 18, "Luka"}


function doSomething(ragaca)
    return ragaca
end


local param1 = "weyw ywerywe"
local result = doSomething(param1)
print(result)